services:
  web:
    build:
      context: ..
      dockerfile: messaging_app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - messaging_net
    volumes:
      - ../messaging_app:/app/messaging_app
      - ../chats:/app/chats
      - ../manage.py:/app/manage.py
  db:
    image: "mysql:8.0"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - messaging_net

networks:
  messaging_net:
volumes:
  messaging_vol:
  mysql_data:
